// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8hR-4FNfuVMZ4ocJ1o3SGPOShnGfrir4',
    appId: '1:670830422226:web:d5add5c10c8c5e91ede50b',
    messagingSenderId: '670830422226',
    projectId: 'fir-demo-a0ced',
    authDomain: 'fir-demo-a0ced.firebaseapp.com',
    storageBucket: 'fir-demo-a0ced.firebasestorage.app',
    measurementId: 'G-KPYNQKY7T2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkrf5dlxhXTEJon96q9ukd5XQttILM-T4',
    appId: '1:670830422226:android:5de8a92bc8146808ede50b',
    messagingSenderId: '670830422226',
    projectId: 'fir-demo-a0ced',
    storageBucket: 'fir-demo-a0ced.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDcU_5Inl1R6EjtRlGW2UoeRlcGRyPGzhw',
    appId: '1:670830422226:ios:07602c6a1e76c575ede50b',
    messagingSenderId: '670830422226',
    projectId: 'fir-demo-a0ced',
    storageBucket: 'fir-demo-a0ced.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDcU_5Inl1R6EjtRlGW2UoeRlcGRyPGzhw',
    appId: '1:670830422226:ios:07602c6a1e76c575ede50b',
    messagingSenderId: '670830422226',
    projectId: 'fir-demo-a0ced',
    storageBucket: 'fir-demo-a0ced.firebasestorage.app',
    iosBundleId: 'com.example.firebasedemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8hR-4FNfuVMZ4ocJ1o3SGPOShnGfrir4',
    appId: '1:670830422226:web:e8fc2a193ec39082ede50b',
    messagingSenderId: '670830422226',
    projectId: 'fir-demo-a0ced',
    authDomain: 'fir-demo-a0ced.firebaseapp.com',
    storageBucket: 'fir-demo-a0ced.firebasestorage.app',
    measurementId: 'G-F36X6FR6P9',
  );
}
