// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOQlVLTpyHlaNAcV8Vm1rZWLi9cbot8cE',
    appId: '1:217011573829:web:aea6c63fd751dcc0a5bf2c',
    messagingSenderId: '217011573829',
    projectId: 'fir-authentication-1887c',
    authDomain: 'fir-authentication-1887c.firebaseapp.com',
    storageBucket: 'fir-authentication-1887c.firebasestorage.app',
    measurementId: 'G-FDZ9F6XQ0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL00M3FBC2531yoZveFnzOoVk4Qu5RuyY',
    appId: '1:217011573829:android:0d81156af3e69cf0a5bf2c',
    messagingSenderId: '217011573829',
    projectId: 'fir-authentication-1887c',
    storageBucket: 'fir-authentication-1887c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgOU_s4K4XTXzp8jiJBNGRLv1mJkwhlJY',
    appId: '1:217011573829:ios:4e20824cce7dd11da5bf2c',
    messagingSenderId: '217011573829',
    projectId: 'fir-authentication-1887c',
    storageBucket: 'fir-authentication-1887c.firebasestorage.app',
    iosClientId: '217011573829-l98b0ncu3tn1glnh662nnk84fi620k1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGoogleAuthentications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCgOU_s4K4XTXzp8jiJBNGRLv1mJkwhlJY',
    appId: '1:217011573829:ios:4e20824cce7dd11da5bf2c',
    messagingSenderId: '217011573829',
    projectId: 'fir-authentication-1887c',
    storageBucket: 'fir-authentication-1887c.firebasestorage.app',
    iosClientId: '217011573829-l98b0ncu3tn1glnh662nnk84fi620k1g.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseGoogleAuthentications',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOQlVLTpyHlaNAcV8Vm1rZWLi9cbot8cE',
    appId: '1:217011573829:web:abd79ddcb9c8d0d3a5bf2c',
    messagingSenderId: '217011573829',
    projectId: 'fir-authentication-1887c',
    authDomain: 'fir-authentication-1887c.firebaseapp.com',
    storageBucket: 'fir-authentication-1887c.firebasestorage.app',
    measurementId: 'G-69VJFM81RH',
  );
}
